### ISSUE TITLE
Add "add-host" and hostname when running docker.

### ISSUE THREAD

**Issue by lucaluo** [ddragosd/tsung-docker#1]
Thanks for your great docker image! I was new to tsung. When I started with your script, it took me quite a while to find out I need to set both hostname and add hostnames in /etc/hosts. I suggest to add `--add-host` and `-h` in your getting started example to help newbies like me get started easier.

The script I use for master node:

```
docker run -d \
  -p 21:22 \
  -p 4369:4369 \
  --add-host tsung_slave1:10.132.35.108 \
  --add-host tsung_slave2:10.132.35.109 \
  --add-host target:10.132.35.110 \
  -h tsung_master \
  --name tsung \
  ddragosd/tsung-docker:latest -f /usr/local/tsung/tsung.xml start
```

Slave node:

```
docker run -d \
  -p 21:22 \
  -p 4369:4369 \
  -e "SLAVE=true" \
  -h tsung_slave1 \
  --add-host tsung_master:10.132.35.107 \
  --add-host target:10.132.35.110 \
  --name tsung_slave \
  ddragosd/tsung-docker:latest
```

**Comment by ddragosd** [comment]
@jiaxiluo thanks for mentioning this. I will add this to the documentation. 

I have been trying to run this in Marathon actually, hence the small script [tsung-update-hosts.sh](https://github.com/ddragosd/tsung-docker/blob/master/scripts/tsung-update-hosts.sh) that automatically discovers the nodes in the cluster.
