### ISSUE TITLE
License for the project

### ISSUE THREAD

**Issue by thachmai** [ddragosd/tsung-docker#2]
Could you clarify the licensing terms of the code? I'm interested in forking the project but am not sure if I can without a license.

http://stackoverflow.com/questions/4007674/whats-the-default-license-of-code-published-at-github

**Comment by ddragosd** [comment]
oh, thanks for mentioning. I've no intention to keep this closed, so I'm thinking to add Apache 2.0 license. This should do it for you, right ?

I still need to write documentation on the best way to run this container with Marathon, as that was my main goal for this container and that's how I'm using it at the moment. Marathon makes it very easy to scale up and down the slaves.

![image](https://cloud.githubusercontent.com/assets/541933/7624252/9e98b2d2-f99a-11e4-9cdc-828fee71c30e.png)

If you find an easier way I'm interested.

**Comment by thachmai** [comment]
Apache is awesome. Thanks :)
